server:
  port: 8184

spring:
  jpa:
    open-in-view: false
    show-sql: true
#    database-platform: org.hibernate.dialectPostgresSQL9Dialect
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialectPostgresSQL9Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=customer&binaryTransfer=true&reWriteBatchInserts=true&springtype=unspecified
    username: postgres
    password: manoseni6.
    driver-class-name: org.postgresql.Driver
    platform: postgres
    schema: classpath:init-schema.sql
    data: classpath:init-data.sql
    initialization-mode: always
